language: php
php:
  - '7.3'
  - '7.4'
#  - nightly
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `FRC-Portal`;'
install:
  - composer install -d ./api/app/
  - composer dump-autoload -d ./api/app/
before_script:
  - cp ./api/app/secured/config.example.ini ./api/app/secured/config.ini
  - php ./api/app/database/_CreateDatabase.php
