language: php
php:
  - '7.3'
  - '7.4'
#  - nightly
services:
  - mysql
install:
  - cp ./api/app/secured/config.example.ini ./api/app/secured/config.ini
  - composer install -d ./api/app/
  - composer dump-autoload -d ./api/app/
  - php ./app/api/database/_CreateDatabase.php
