language: php
php:
  - '7.2'
  - '7.3'
  - '7.4'
#  - nightly
jobs:
  allow_failures:
    - php: '7.4'
env:
  global:
    - DB_HOST="localhost"
    - DB_USER="root"
    - DB_PASS=
    - DB_NAME="FRC-Portal"
    - NO_DB_PASS=true
services:
  - mysql
before_script:
  - if php -v | grep -q 'Xdebug'; then phpenv config-rm xdebug.ini; fi
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS `FRC-Portal`;'
  - composer self-update
install:
  - composer install -d ./api/app/
  - composer dump-autoload -d ./api/app/
before_script:
#  - cp ./api/app/secured/config.example.ini ./api/app/secured/config.ini#
  - php ./api/app/initialInstall.php
script: phpdbg -qrr ./api/app/vendor/bin/phpunit -c ./api/app/phpunit.xml --verbose --testdox
